on: [push]
jobs:
  tests:
    runs-on: docker
    container:
      image: codeberg.org/jwijenbergh/ci:latest-amd64
    steps:
      - name: Clone Repository
        run: |
          git clone --depth 1 -b ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .
      - name: Build
        run: |
          unshare -c -n make all
      - name: Lint
        run: |
          unshare -c -n make lint
